### ISSUE TITLE
Feature request: ini files with space indent

### ISSUE THREAD

**Issue by lcnittl** [macisamuele/language-formatters-pre-commit-hooks#100]
Thanks for providing these nice hooks!

I was wondering, whether you would be willing to add an argument to the `pretty-format-ini` hook, that would allow to have spaces, rather than tabs for indents.

The reason for this is that many tools for checking and fixing config files would insert spaces (eg [setup-cfg-fmt](https://github.com/asottile/setup-cfg-fmt), [tox-ini-fmt](https://github.com/tox-dev/tox-ini-fmt)), ending up in a tab→space→tab (or space→tab→space) loop.

Thanks for your consideration,
lcnittl

**Comment by macisamuele** [comment]
@lcnittl I'm not sure I would have the bandwidth to look into it, but PR are always welcome.
If you feel like it it a feature nice to have on the tool, I'll be more than happy to have it merged.

**Comment by macisamuele** [comment]
@Delgan could be possible to eventually extend `config_formatter` to support indentation via `\t` instead of spaces?
Assuming that we could do it then it should not be hard to expose the feature into the pre-commit hook

**Comment by macisamuele** [comment]
you do raise very good points 😅

let me think a bit more about it
having customisation is good but it does come to a cost of maintaining code and having style discussions that the pre commit hooks were aiming to reduce.

**Comment by macisamuele** [comment]
I checked this again and
1. visual indentation would depend on your _editor_ configuration (tab is equivalent to 2 spaces, 4 spaces, n spaces)
2. general mixing of tabs and spaces might lead to unexpected results as parsing of the INI file might lead to different assumptions whether the indentation is space or tab


If you can provide a *valid* use-case where this feature is needed please feel free to re-open the issue and we can re-think about this.
But without further understanding on why we would like to support this I would agree with @Delgan insights and I would rather prefer not to support custom indentation style within the tool.

cc: @lcnittl
