### ISSUE TITLE
Add possibility to define formatter (jar) file

### ISSUE THREAD

**Issue by fabasoad** [macisamuele/language-formatters-pre-commit-hooks#119]
**Reasoning**

Some of the companies have strict rules in terms of downloading binaries from external storages. In this case `jar` file is downloaded from external storage which is prohibited in many companies (as many companies use own artifact storage such as Artifactory or GHES).

**Proposition**

Add a possibility to define path to the jar file, either local one or web.

**Benefits**

- Increase security as it is not needed to download jar from external storage
- In case of local path - increasing speed as it is not needed to download jar everytime

**Comment by macisamuele** [comment]
Not opposed to similar changes, please provide a PR and I will be happy to merge it.

**Comment by fabasoad** [comment]
Hi @macisamuele! PR has been created. Please review. Thanks!
