### ISSUE TITLE
Unblock ktlint with JDK 17

### ISSUE THREAD

**Issue by harti2006** [macisamuele/language-formatters-pre-commit-hooks#122]
Hey together, I'm using this tool for my Kotlin projects and would like to migrate to Java 17 soon.
At the moment there is an assertion that ktlint can only be run with Java <16, but I think this is actually obsolete. I was able to run ktlint with Java 17 and even Java 19.

Would you be up to remove this Java constraint in the pre-commit hook?

**Comment by macisamuele** [comment]
Releasing v2.5.0
