### ISSUE TITLE
Add option to set different log level

### ISSUE THREAD

**Issue by TribuneX** [macisamuele/language-formatters-pre-commit-hooks#168]
Currently `ktlint` is called with log level [debug](https://github.com/macisamuele/language-formatters-pre-commit-hooks/blob/master/language_formatters_pre_commit_hooks/pretty_format_kotlin.py#L83) which leads to a lot of log messages in case the hook is failing. It is sometimes hard to spot the actual rule violation. What about allowing to configure the log level to e.g. `INFO`?

**Comment by macisamuele** [comment]
Thanks for the report.
This seems something that would be addressed already in #163

**Comment by TribuneX** [comment]
Thx. This should address the large log output issue. Looking forward to this update.
