### ISSUE TITLE
Java format hook does not work on Java 1.8

### ISSUE THREAD

**Issue by vitalca** [macisamuele/language-formatters-pre-commit-hooks#171]
The `--add-exports` command line option was added in Java 9.
When running on Java 1.8, you don't need to add these exports. Java fails to start.

Unfortunately, a lot of enterprise legacy code still uses JDK 1.8, This version is going to be [supported ](https://endoflife.date/java) till the end of 2030.

As a workaround I've added an alias to my `~/.bashrc`, and I run `gitc` instead of `git commit`:
```
alias gitc='PATH=~/.sdkman/candidates/java/17/bin:$PATH git commit'
```

**Comment by macisamuele** [comment]
I'm not a bit Java expert and I'll try to document myself a bit more.
In the meantime on the link you have referenced there is no trace of 1.8 version.
Something worth mentioning is that recent versions of Google Java Formatter would not work without the add exports, which implies that you won't be able to run them on your java version.

**Comment by vitalca** [comment]
Hi Samuele,

> In the meantime on the link you have referenced there is no trace of 1.8 version.

Java `1.8` == Java `8`, so it is mentioned over there.

Please look at the code in the [pretty_format_java.py](https://github.com/macisamuele/language-formatters-pre-commit-hooks/blob/master/language_formatters_pre_commit_hooks/pretty_format_java.py#L99).

According to the [google-java-format/README](https://github.com/google/google-java-format#as-a-library), the  `--add-exports` JVM flags are required when running on JDK 16 and newer.

What needs to be done is the following.
1) check java version (there is a function for this)
2) for any versions `>= 16`, you add the `--add-exports` arguments.
3) for all versions below `16` you do not add them.

That's it. Thanks 🙂

**Comment by vitalca** [comment]
Google Formatter does not start on JDK 8.
Sorry for bothering.

**Comment by macisamuele** [comment]
Thanks for the the report and carrying the check already.
