### ISSUE TITLE
Make ktlint log level configurable (or at least avoid debug logging when autofix is enabled)

### ISSUE THREAD

**Issue by Velfi** [macisamuele/language-formatters-pre-commit-hooks#176]
In the [ktlint python script](https://github.com/macisamuele/language-formatters-pre-commit-hooks/blob/7fa2c3a1fd937142ffb73115a77032734df848da/language_formatters_pre_commit_hooks/pretty_format_kotlin.py#L97), `ktlint` is run with `--log-level=debug`.

This slows down the pre-commit check and I personally find it to be noisy. Would you entertain the idea of setting the default to `info` instead of `debug` or making it possible to configure/disable the logging?

**Comment by macisamuele** [comment]
Thanks for the report.
As we collect failures via JSON reporter, I think that overriding the logging level is no longer needed.
Feel free to open a PR where the log level definition is removed and I'll be happy to approve it.
