### ISSUE TITLE
better package name?

### ISSUE THREAD

**Issue by brodybits** [macisamuele/language-formatters-pre-commit-hooks#186]
This looks like a really nice little CLI toolset. I originally found this while searching for a Python TOML formatting tool, this is how I found the underlying `toml-sort` tool as I said in #185. And the built-in `pretty_format_ini` script gives me a handy CLI wrapper around the `config-formatter` library.

I suspect it should be no problem to rename this project and either add dual package publishing or just deprecate the one with the longer name.

In any case, a big THANK YOU for this toolset!!

**Comment by macisamuele** [comment]
This library is mainly meant to provide pre-commit hooks tools to format files.
To achieve so it the library does also expose handy binaries.

Not sure of what you have in mind with double publishing or renaming.
To be clear the provided tools are for a miscellaneous of different languages.
