### ISSUE TITLE
Is an argument available to disable logging the output below for each file when the hook runs for formatting java and kotlin?

### ISSUE THREAD

**Issue by dustinsand** [macisamuele/language-formatters-pre-commit-hooks#20]
For example:

[cwd=/Users/foo] Run command: java -jar /Users/foo/.cache/pre-commit/google-java-format-1.7-all-deps.jar  --replace src/main/java/com/Foo.java
[return_code=0] | 
[cwd=/Users/foo] Run command: java -version
[return_code=0] | openjdk version "1.8.0_252"
OpenJDK Runtime Environment Corretto-8.252.09.1 (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM Corretto-8.252.09.1 (build 25.252-b09, mixed mode)

**Comment by cortinico** [comment]
Hey @dustinsand,
Unfortunately we don't expose a flag for running in quite mode. Specifically for `ktlint` we hardcode the `--verbose` here:

https://github.com/macisamuele/language-formatters-pre-commit-hooks/blob/f221f468b130276372591f363db03aa7d20a75e6/language_formatters_pre_commit_hooks/pretty_format_kotlin.py#L46-L52

A PR to expose the logging level is more than welcome 👍

**Comment by macisamuele** [comment]
By default pre-commit does not show any output if there are no failures.
Would be possible to have a "toy" repository where we can have a reproduction of the issue?

**Comment by dustinsand** [comment]
Hi @cortinico and @macisamuele ,

Well, I'm embarrassed, I forgot I put --verbose on the make target which was used to force run all the pre-commit hooks.  For example,

pre-commit run --all-files --verbose

After I removed '--verbose' the log output is not shown as you described.  My apologies for the confusion.
