### ISSUE TITLE
rare releases

### ISSUE THREAD

**Issue by eirnym** [macisamuele/language-formatters-pre-commit-hooks#212]
Could you please do releases a bit more often? The most important parts for me is formatter updates

**Comment by macisamuele** [comment]
Given the absence of new features I'm wondering what is the hidden ask beyond this.

Is there something that I'm missing or features that were supposed to be released on not released yet?

Please give me more information such that I can react accordingly.

**Comment by eirnym** [comment]
These tools are released quite often. I see this important enough to release the hooks

**Comment by macisamuele** [comment]
I can understand and next week I'll be releasing a new version.
In the meantime:
* hooks can be configured to use a specific commit sha from this repository (`rev: {LATEST_SHA_OR_VERSION}`)
* most of the pre-commit hooks allow for users to change the version of the external tool used.
  By default it does use the version defined within the release, but it can be altered with arguments like `--google-java-formatter-version`

**Comment by eirnym** [comment]
I understand your point. 

Sha version isn't a semver and a person needs a full commit history to tell which gir revision is created later than other one. E.g. `aaaaaa` could be after `bbbbbb`. 


Specific tool versions are not a very good idea either as tools such as Dependabot or RenovateBot will never pick version automatically. I theoretically can create a hook for renovate bot, but it would be way more complicated than upgrade tools on your side with the same tools and make releases more often.

**Comment by macisamuele** [comment]
To be clear, I'm not suggesting to use the workaround as stable solutions but rather as mitigations until a release is provided.

Your point on absent release is fair and I should have released them earlier even if there were no functional updates of the tool and I'm sorry for that.

As of now v2.13.0 has been released hence no workarounds are going to be needed.
