### ISSUE TITLE
Request: `pretty-format-toml` `--no-sort` to also avoid sorting groups

### ISSUE THREAD

**Issue by Avasam** [macisamuele/language-formatters-pre-commit-hooks#231]
Hi! I'd like to avoid sorting groups for `pretty-format-toml`. We organize groups in a way that has semantic value and make sense for a human, but isn't necessarily in alphabetical order.
It seems `--no-sort` only applies to keys. I'd like it to also apply to groups, or have a different flag that lets me avoid sorting groups.

**Comment by macisamuele** [comment]
The goal of the pre-commit hook is to provide a consistent formatting of a given content.
To avoid bikeshedding a single sorting method is preferred.

At the same time the underlying libraries do not expose such functionalities and implementing them would be opposite to the spirit of the library.

I appreciate the feedback but I don't think that this is a feature that I would be implementing.
