### ISSUE TITLE
pre-commit requires python3.10

### ISSUE THREAD

**Issue by eirnym** [macisamuele/language-formatters-pre-commit-hooks#232]
Hi, 

pre-commit used in this project requires python 3.10. Currently i have python 3.12 as a primary python version and python 3.13 will out.

What exactly is holding this project to use available Python 3, not the specific version? 

In my projects I use matrix to test on multiple versions

**Comment by macisamuele** [comment]
Are you referring to the python version defined in the tox environment?

**Comment by eirnym** [comment]
I refer to pre-commit hooks specifically, tox works fine on my local environment.

**Comment by macisamuele** [comment]
I could bump it , but the main reason to not have it automatically pick any python3 version available is to make sure that the execution is predictable.

**Comment by eirnym** [comment]
I understand. What is the impact of removing these lines if this project explicitly specifies Python 3 as a Python for development?

**Comment by macisamuele** [comment]
That pre-commit hooks could be rub with unpredictable python version (let's say python3.6) and some dependencies might no longer be installable.
Alternative is that behaviour changes might lead to surprising differences.

As of this I don't plan to relax the python version to any python3 available.
Still, I would be open to bump the version if this facilitate the development

**Comment by macisamuele** [comment]
Updated to python 3.12.
Considering this closed
