### ISSUE TITLE
Backward compatibility .pre-commit-hooks.yaml

### ISSUE THREAD

**Issue by lcnittl** [macisamuele/language-formatters-pre-commit-hooks#25]
The use of `files` for backward compatibility seems to defeat the added flexibility by `types`.

https://github.com/macisamuele/language-formatters-pre-commit-hooks/blob/72e5e0c0d66fab069e77bac41a17afd3e456b86d/.pre-commit-hooks.yaml#L14-L16

While there are, currently, [2 extensions and 5 files mapped to `ini` type](https://github.com/chriskuehl/identify/blob/61deb722cf4dd6a82d57f2e242b208da2fb84bc2/identify/extensions.py), pinning `files` to `*.ini` extension will result in only 1 extension (`ini` itself) being matched.

    '*.ini'
    '*.txsprofile'

    '.coveragerc'
    '.gitconfig'
    '.hgrc'
    '.pypirc'
    'setup.cfg'

Would it not be better to remove the `files` key and have people that do need backward compatibility add them in their `.pre-commit-hooks.yaml`. (Same applies to other hooks)

Thanks for your consideration!

**Comment by cortinico** [comment]
You're right. We should update `files` to:

```
 types: [ini] 
   # for backward compatibility 
 files: '' 
```

Source: https://github.com/pre-commit/pre-commit/pull/551#issuecomment-312535540
