### ISSUE TITLE
in windows，can not download google format jar

### ISSUE THREAD

**Issue by ufwtlsb** [macisamuele/language-formatters-pre-commit-hooks#28]
error：
**PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。**
means file not close

in utils：
```
    with tempfile.NamedTemporaryFile(delete=False) as tmp_file:  # Not delete because we're renaming it
        shutil.copyfileobj(r.raw, tmp_file)
        tmp_file.flush()
        os.fsync(tmp_file.fileno())
        tmp_file.close()  # add this is ok
        os.rename(tmp_file.name, final_file)
```

**Comment by macisamuele** [comment]
@ufwtlsb thanks for reporting the issue.
I did not check the execution on windows but I'm letting github actions identify regressions and we can replicate the issue ([here](https://github.com/macisamuele/language-formatters-pre-commit-hooks/runs/1140263665?check_suite_focus=true))

In the meantime I would recommend to use the released version (1.5.0) which should not be affected by the issue or using revision 72e5e0c0d66fab069e77bac41a17afd3e456b86d if you need features added after the latest release.
