### ISSUE TITLE
Pretty format YAML issue with multiline strings

### ISSUE THREAD

**Issue by nvmker** [macisamuele/language-formatters-pre-commit-hooks#47]
Hi,
Looks like pretty format yaml hook formatting multiline strings in YAML sequence to single line.
For example I have this:

```
sequence:
  - very long line which need to be mulitine
    second part of multine string
```

Pretty format YAML converts this example to this:

```
sequence:
  - very long line which need to be mulitine second part of multine string
```

**Comment by macisamuele** [comment]
Hello @nvmker your input yaml does not contain a YAML multiline string
```
>>> import yaml
>>> text = """sequence:
  - very long line which need to be mulitine
    second part of multine string
"""
>>> print(text)
sequence:
  - very long line which need to be mulitine
    second part of multine string

>>> yaml.safe_load(text)
{'sequence': ['very long line which need to be mulitine second part of multine string']}
```

You can find examples of such strings on https://yaml-multiline.info/
If you still want to ensure that the line (as very long) is split over multiple lines you could be using `>` as in the example

```yaml
sequence:
- >
  very long line which need to be mulitine
  second part of multine string
```

```
>>> import yaml
>>> text = """sequence:
- >
  very long line which need to be mulitine
  second part of multine string"""
>>> yaml.safe_load(text)
{'sequence': ['very long line which need to be mulitine second part of multine string']}
```

**Comment by nvmker** [comment]
My example is also valid according to official YAML specification: https://yaml.org/spec/1.2/spec.html#id2760844
See Example 2.18. Multi-line Flow Scalars

**Comment by macisamuele** [comment]
@nvmker with "YAML multiline string" I meant a YAML string that reflect to multiple line _text_ when loaded.

I'm not saying that it is not valid, because it is (and I've also showed it by loading the YAML content) but rather that the formatter sees that as a single line string and as such it behaves.

If you really want the string to be preserved into multiple lines you need to hint that you want to have the line style preserved (with `>`). This is not YAML specifications but how the prettier-tool work :)

**Comment by nvmker** [comment]
I think I didn't explain it correctly, I mean by my example that the multiline string need to be converted into single line with converting ```\n``` to spaces. For example I have an array with very long shell commands which need to be preserved as single line commands, but since it's a long commands I want to split it into a few lines.

**Comment by macisamuele** [comment]
If you have trouble with EOL you might wrap the lines with quotes like in
```yaml
sequence:
- "very long line which need to be mulitine
  second part of multine string"
```

```
>>> import yaml
>>> text = """sequence:
- "very long line which need to be mulitine
  second part of multine string"
"""
>>> yaml.safe_load(text)
{'sequence': ['very long line which need to be mulitine second part of multine string']}
```

The provided example will be considered "pretty" from the tool, so this might resolve your concern.

At the current state we don't support a maximum line length (even as suggestion) in the prettier tool.

I'm not necessarily a big fan of such configurations (as I would rather prefer a configuration-less tool) but I'm not opposed to review and eventually accept PRs that are meant to improve it.
