### ISSUE TITLE
Removing quotes from time of day string may result in integer

### ISSUE THREAD

**Issue by l0b0** [macisamuele/language-formatters-pre-commit-hooks#53]
Filed in relation to https://github.com/dependabot/dependabot-core/issues/3263, since it's not clear who's at fault.

To reproduce:

1. Put a key/value pair like `time: "15:00"` in a YAML file
2. Run `pretty-format-yaml --autofix` on the file

Result:

The key/value pair is changed to `time: 15:00`.

It looks like this clashes with the sexagesimal (base 60) definition of [YAML integers](https://yaml.org/type/int.html), effectively turning the original string into an integer value.

**Comment by CafeLungo** [comment]
I see similar happening with a string value "no" being turned into a boolean because it removes the quotes. Specifically, in a docker-compose file, on restart-policy:
```
restart: "no"     # needs to be a string
```
which then results in:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.myapp.restart contains an invalid type, it should be a string
```

**Comment by Skylion007** [comment]
@lbo just use         "--preserve-quotes",
