### ISSUE TITLE
pretty-format-java only supports AOSP

### ISSUE THREAD

**Issue by ChenAndrew** [macisamuele/language-formatters-pre-commit-hooks#7]
this should not use AOSP as a default

**Comment by macisamuele** [comment]
What do you have in mind?
Currently the library uses the default configuration so of the google java formatter, are you suggesting to expose underlying parameter support to allow customisations?

Can you elaborate more?

**Comment by ChenAndrew** [comment]
Usage: google-java-format [options] file(s)

Options:
  -i, -r, -replace, --replace
    Send formatted output back to files, not stdout.
  -
    Format stdin -> stdout
  --assume-filename, -assume-filename
    File name to use for diagnostics when formatting standard input (default is <stdin>).
  --aosp, -aosp, -a
    Use AOSP style instead of Google Style (4-space indentation).
  --fix-imports-only
    Fix import order and remove any unused imports, but do no other formatting.
  --skip-sorting-imports
    Do not fix the import order. Unused imports will still be removed.
  --skip-removing-unused-imports
    Do not remove unused imports. Imports will still be sorted.
 . --skip-reflowing-long-strings
    Do not reflow string literals that exceed the column limit.
 . --skip-javadoc-formatting
    Do not reformat javadoc.
  --dry-run, -n
    Prints the paths of the files whose contents would change if the formatter were run normally.
  --set-exit-if-changed
    Return exit code 1 if there are any formatting changes.
  --lines, -lines, --line, -line
    Line range(s) to format, like 5:10 (1-based; default is all).
  --offset, -offset
    Character offset to format (0-based; default is all).
  --length, -length
    Character length to format.
  --help, -help, -h
    Print this usage statement.
  --version, -version, -v
    Print the version.
  @<filename>
    Read options and filenames from file.

If -i is given with -, the result is sent to stdout.
The --lines, --offset, and --length flags may be given more than once.
The --offset and --length flags must be given an equal number of times.
If --lines, --offset, or --length are given, only one file (or -) may be given.

google-java-format: Version 1.8
https://github.com/google/google-java-format

My suggestion is to get rid of the --aosp flag as that changes the formatting style to AOSP instead of Google style

**Comment by macisamuele** [comment]
Do you have bandwidth to post a PR for this?

The style change should be done in a backward compatible way to avoid users of this hooks to have all their file changed.
Essential this means that a new CLI argument should be added to allow usage of google style.

If this seems too involved I could be ok to have it defaulted to google style but we should support AOSP style via CLI flag.

**Comment by ChenAndrew** [comment]
https://github.com/macisamuele/language-formatters-pre-commit-hooks/pull/8

**Comment by ChenAndrew** [comment]
Probably best to have Google style as a default going forward instead of defaulting to AOSP

**Comment by macisamuele** [comment]
@ChenAndrew that's a matter of preference.
Personally I do use the pre-commit mostly on android specific repos and so having AOSP is actually preferable over Google style.
But as far as we have it configurable I'm fine.
