### ISSUE TITLE
[REQUEST] Release new tag

### ISSUE THREAD

**Issue by Polpetta** [macisamuele/language-formatters-pre-commit-hooks#98]
Hi,
it is possible to get a new tag after #97 is merged?

I know that `pre-commit` supports using SHA commits as `rev`, but I'd feel more "safe" to have a versioned tag to refer to.

Thank you for you project and dedication.

**Comment by cortinico** [comment]
Yup @macisamuele can help you here

**Comment by macisamuele** [comment]
I'll be trying to release a new version in the next hours

**Comment by Polpetta** [comment]
Thank you very much!! :tada:
